### ISSUE TITLE
Error : gen_screwDislocation.py

### ISSUE THREAD

**Issue by Rana-Phy** [peizong/DIST-Toolkit#1]
Thanks for DIST.
However, I am getting the following error!
![Capture](https://user-images.githubusercontent.com/56949120/77435443-ab007280-6e25-11ea-976e-63322070ac07.PNG)

I used the disl.file.in files as you suggested in your paper.

[disl.file.in.txt](https://github.com/peizong/DIST-Toolkit/files/4375751/disl.file.in.txt)

How can I execute the script properly?
I am waiting to hear from you.

**Comment by peizong** [comment]
Dear Rana,

  sorry for the late response. It seems your line 6 for the atom numbers are not all integers. This happens very often for windows users, because linux and windows use different method to end a line. Could you please type that line by hand, and try again?
  Please let me know if you still have problems.
  Thanks for your interest. 

@Rana-Phy

Best regards,
Zongrui

**Comment by peizong** [comment]
I did not login my account very often, but I will do so in the future. Please write me email if I cannot respond timely. peizongrui@gmail.com.
@Rana-Phy

**Comment by peizong** [comment]
The issue has been resolved.
